#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
═══════════════════════════════════════════════════════════════════════════════
  diskstats.py — a cross-platform disk & storage report
═══════════════════════════════════════════════════════════════════════════════

  Shows filesystem usage, physical drives, and ZFS pool health in a clean,
  colorized layout that reads well in a terminal or an email body.

  Supported platforms : macOS · Linux · FreeBSD
  Requires            : Python 3.6+  (standard library only)

  Usage:
      ./diskstats.py            # colorized terminal output
      ./diskstats.py --no-color # plain text (good for emails / logs)
      ./diskstats.py --html     # inline-styled HTML (for HTML emails)
      ./diskstats.py --help     # show options

  Author : generated by Claude
  License: MIT
═══════════════════════════════════════════════════════════════════════════════
"""

from __future__ import annotations

import argparse
import os
import platform
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from typing import Iterable, List, Optional, Sequence, Tuple

# ─────────────────────────────────────────────────────────────────────────────
#  CONSTANTS & PALETTE
# ─────────────────────────────────────────────────────────────────────────────

SCRIPT_VERSION = "1.0.0"

# Box-drawing glyphs — kept in one place so the whole look can be retuned fast.
GLYPHS = {
    "tl": "╭", "tr": "╮", "bl": "╰", "br": "╯",
    "h":  "─", "v":  "│",
    "lt": "├", "rt": "┤",
    "bar_full":  "█",
    "bar_empty": "░",
    "bullet":    "•",
    "arrow":     "›",
    "check":     "✓",
    "warn":      "!",
    "cross":     "✗",
}


class Palette:
    """ANSI color codes. Disabled at construction time if color is off."""

    def __init__(self, enabled: bool = True) -> None:
        def c(code: str) -> str:
            return code if enabled else ""

        self.reset  = c("\033[0m")
        self.bold   = c("\033[1m")
        self.dim    = c("\033[2m")
        self.italic = c("\033[3m")

        # Foregrounds
        self.fg_default = c("\033[39m")
        self.fg_black   = c("\033[30m")
        self.fg_red     = c("\033[38;5;203m")
        self.fg_green   = c("\033[38;5;114m")
        self.fg_yellow  = c("\033[38;5;221m")
        self.fg_blue    = c("\033[38;5;75m")
        self.fg_magenta = c("\033[38;5;176m")
        self.fg_cyan    = c("\033[38;5;116m")
        self.fg_white   = c("\033[38;5;252m")
        self.fg_grey    = c("\033[38;5;244m")
        self.fg_orange  = c("\033[38;5;215m")

        # Semantic aliases — use these in the body of the script.
        self.heading  = self.bold + self.fg_cyan
        self.subtle   = self.fg_grey
        self.accent   = self.fg_blue
        self.ok       = self.fg_green
        self.warn     = self.fg_yellow
        self.bad      = self.fg_red
        self.label    = self.bold + self.fg_white
        self.value    = self.fg_white


# ─────────────────────────────────────────────────────────────────────────────
#  DATA MODELS
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Filesystem:
    source: str           # e.g. /dev/disk1s1, tank/home
    mount:  str           # e.g. /, /home
    fstype: str           # e.g. apfs, ext4, zfs
    size:   int           # bytes
    used:   int           # bytes
    avail:  int           # bytes

    @property
    def percent(self) -> float:
        return (self.used / self.size * 100.0) if self.size else 0.0


@dataclass
class Drive:
    name:   str
    size:   Optional[int] = None   # bytes
    model:  Optional[str] = None
    kind:   Optional[str] = None   # SSD / HDD / NVMe / etc.
    extra:  str = ""


@dataclass
class ZPool:
    name:   str
    size:   Optional[int] = None
    alloc:  Optional[int] = None
    free:   Optional[int] = None
    frag:   Optional[str] = None
    cap:    Optional[str] = None   # percent, as reported
    dedup:  Optional[str] = None
    health: str = "UNKNOWN"
    errors: str = ""


@dataclass
class Report:
    hostname: str
    system:   str
    release:  str
    filesystems: List[Filesystem] = field(default_factory=list)
    drives:      List[Drive]      = field(default_factory=list)
    zpools:      List[ZPool]      = field(default_factory=list)
    notes:       List[str]        = field(default_factory=list)


# ─────────────────────────────────────────────────────────────────────────────
#  SHELL HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def run(cmd: Sequence[str], timeout: int = 10) -> Tuple[int, str, str]:
    """Run a command, returning (returncode, stdout, stderr). Never raises."""
    try:
        p = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
        return p.returncode, p.stdout, p.stderr
    except FileNotFoundError:
        return 127, "", f"command not found: {cmd[0]}"
    except subprocess.TimeoutExpired:
        return 124, "", f"timeout: {' '.join(cmd)}"
    except Exception as exc:  # pragma: no cover — defensive
        return 1, "", f"{type(exc).__name__}: {exc}"


def which(name: str) -> bool:
    return shutil.which(name) is not None


def human_bytes(n: Optional[int]) -> str:
    """Format a byte count as a compact human string (e.g. '1.4 TiB')."""
    if n is None:
        return "—"
    if n < 0:
        return "—"
    units = ["B", "KiB", "MiB", "GiB", "TiB", "PiB", "EiB"]
    x = float(n)
    for u in units:
        if x < 1024.0 or u == units[-1]:
            if u == "B":
                return f"{int(x)} {u}"
            return f"{x:.1f} {u}"
        x /= 1024.0
    return f"{n} B"


def parse_size_suffixed(text: str) -> Optional[int]:
    """Parse strings like '1.8T', '931.5G', '512M' into bytes."""
    if not text or text in ("-", "—"):
        return None
    m = re.match(r"^\s*([0-9]+(?:\.[0-9]+)?)\s*([KMGTPEZYkmgtpezy]?)(?:i?B)?\s*$", text)
    if not m:
        return None
    num = float(m.group(1))
    suf = m.group(2).upper()
    mult = {
        "":  1,
        "K": 1024 ** 1,
        "M": 1024 ** 2,
        "G": 1024 ** 3,
        "T": 1024 ** 4,
        "P": 1024 ** 5,
        "E": 1024 ** 6,
    }.get(suf, 1)
    return int(num * mult)


# ─────────────────────────────────────────────────────────────────────────────
#  COLLECTORS — FILESYSTEMS
# ─────────────────────────────────────────────────────────────────────────────

# Pseudo / virtual filesystems we never want to show.
SKIP_FSTYPES = {
    "devfs", "devtmpfs", "tmpfs", "proc", "sysfs", "cgroup", "cgroup2",
    "pstore", "bpf", "mqueue", "debugfs", "tracefs", "securityfs",
    "hugetlbfs", "fusectl", "overlay", "squashfs", "autofs", "nsfs",
    "ramfs", "rpc_pipefs", "configfs", "binfmt_misc", "fuse.portal",
    "fuse.gvfsd-fuse", "fuse.snapfuse",
}

SKIP_MOUNT_PREFIXES = (
    "/dev", "/proc", "/sys", "/run", "/snap", "/var/lib/docker",
    "/var/snap", "/System/Volumes/Preboot", "/System/Volumes/VM",
    "/System/Volumes/xarts", "/System/Volumes/iSCPreboot",
    "/System/Volumes/Hardware", "/System/Volumes/Update",
)


def _keep_fs(fs: Filesystem) -> bool:
    if fs.fstype.lower() in SKIP_FSTYPES:
        return False
    if fs.size == 0:
        return False
    for pref in SKIP_MOUNT_PREFIXES:
        if fs.mount.startswith(pref) and fs.mount != "/":
            return False
    return True


def collect_filesystems() -> List[Filesystem]:
    """Use `df -k` (portable) plus `-T`/`-Y` when available to learn fstype."""
    rc, out, _ = run(["df", "-Pk"])
    if rc != 0:
        rc, out, _ = run(["df", "-k"])
    if rc != 0 or not out:
        return []

    fstype_by_mount: dict[str, str] = {}
    sysname = platform.system()
    if sysname == "Linux":
        rc2, out2, _ = run(["df", "-PkT"])
        if rc2 == 0 and out2:
            for line in out2.splitlines()[1:]:
                parts = line.split()
                if len(parts) >= 7:
                    fstype_by_mount[parts[-1]] = parts[1]
    elif sysname == "FreeBSD":
        rc2, out2, _ = run(["df", "-kT"])
        if rc2 == 0 and out2:
            for line in out2.splitlines()[1:]:
                parts = line.split()
                if len(parts) >= 7:
                    # On FreeBSD df -T: Filesystem Type 1K-blocks Used Avail Capacity Mounted-on
                    fstype_by_mount[parts[-1]] = parts[1]
    elif sysname == "Darwin":
        rc2, out2, _ = run(["df", "-PY"])
        if rc2 == 0 and out2:
            for line in out2.splitlines()[1:]:
                parts = line.split()
                if len(parts) >= 7:
                    fstype_by_mount[parts[-1]] = parts[1]

    results: List[Filesystem] = []
    for line in out.splitlines()[1:]:
        parts = line.split()
        if len(parts) < 6:
            continue
        source = parts[0]
        try:
            size_k = int(parts[1])
            used_k = int(parts[2])
            avail_k = int(parts[3])
        except ValueError:
            continue
        mount = parts[-1]
        fstype = fstype_by_mount.get(mount, "—")
        results.append(Filesystem(
            source=source,
            mount=mount,
            fstype=fstype,
            size=size_k * 1024,
            used=used_k * 1024,
            avail=avail_k * 1024,
        ))

    results = [fs for fs in results if _keep_fs(fs)]
    # Stable ordering: root first, then by mountpoint.
    results.sort(key=lambda f: (f.mount != "/", f.mount))
    return results


# ─────────────────────────────────────────────────────────────────────────────
#  COLLECTORS — DRIVES
# ─────────────────────────────────────────────────────────────────────────────

def collect_drives_linux() -> List[Drive]:
    if not which("lsblk"):
        return []
    rc, out, _ = run([
        "lsblk", "-dn",
        "-o", "NAME,SIZE,MODEL,ROTA,TRAN,TYPE",
        "--bytes",
    ])
    if rc != 0:
        return []
    drives: List[Drive] = []
    for line in out.splitlines():
        parts = line.split(None, 5)
        if len(parts) < 6:
            continue
        name, size_s, model, rota, tran, typ = (
            parts[0], parts[1], parts[2], parts[3], parts[4], parts[5]
        )
        if typ.lower() not in ("disk",):
            continue
        try:
            size_b: Optional[int] = int(size_s)
        except ValueError:
            size_b = None
        if tran.lower() == "nvme":
            kind = "NVMe SSD"
        elif rota == "0":
            kind = "SSD"
        elif rota == "1":
            kind = "HDD"
        else:
            kind = tran or "—"
        drives.append(Drive(name=f"/dev/{name}", size=size_b,
                            model=model.strip() or None, kind=kind))
    return drives


def collect_drives_macos() -> List[Drive]:
    if not which("diskutil"):
        return []
    rc, out, _ = run(["diskutil", "list"])
    if rc != 0:
        return []
    drives: List[Drive] = []
    # Find each physical `/dev/diskN` header line, then query it.
    for line in out.splitlines():
        m = re.match(r"^(/dev/disk\d+)\s*\(([^)]*)\):", line)
        if not m:
            continue
        dev, desc = m.group(1), m.group(2)
        if "synthesized" in desc.lower():
            # APFS synthesized containers — skip, they're not hardware.
            continue
        rc2, info, _ = run(["diskutil", "info", dev])
        if rc2 != 0:
            continue
        model = None
        size_b: Optional[int] = None
        kind = "—"
        for info_line in info.splitlines():
            il = info_line.strip()
            if il.startswith("Device / Media Name:"):
                model = il.split(":", 1)[1].strip()
            elif il.startswith("Disk Size:"):
                mm = re.search(r"\(([0-9]+) Bytes\)", il)
                if mm:
                    size_b = int(mm.group(1))
            elif il.startswith("Solid State:"):
                val = il.split(":", 1)[1].strip().lower()
                if val == "yes":
                    kind = "SSD"
                elif val == "no":
                    kind = "HDD"
            elif il.startswith("Protocol:"):
                proto = il.split(":", 1)[1].strip()
                if "NVMe" in proto and kind in ("SSD", "—"):
                    kind = "NVMe SSD"
        drives.append(Drive(name=dev, size=size_b, model=model, kind=kind,
                            extra=desc))
    return drives


def collect_drives_freebsd() -> List[Drive]:
    if not which("geom"):
        # Fall back to sysctl.
        drives: List[Drive] = []
        rc, out, _ = run(["sysctl", "-n", "kern.disks"])
        if rc != 0:
            return []
        for name in out.split():
            size_b: Optional[int] = None
            rc2, out2, _ = run(["diskinfo", name])
            if rc2 == 0 and out2:
                parts = out2.split()
                if len(parts) >= 3:
                    try:
                        size_b = int(parts[2])
                    except ValueError:
                        size_b = None
            drives.append(Drive(name=f"/dev/{name}", size=size_b))
        return drives

    rc, out, _ = run(["geom", "disk", "list"])
    if rc != 0:
        return []
    drives = []
    cur: Optional[Drive] = None
    for raw in out.splitlines():
        line = raw.rstrip()
        m = re.match(r"^Geom name:\s*(\S+)", line)
        if m:
            if cur is not None:
                drives.append(cur)
            cur = Drive(name=f"/dev/{m.group(1)}")
            continue
        if cur is None:
            continue
        s = line.strip()
        if s.startswith("Mediasize:"):
            mm = re.search(r"([0-9]+)\s*\(", s)
            if mm:
                cur.size = int(mm.group(1))
        elif s.startswith("descr:"):
            cur.model = s.split(":", 1)[1].strip()
        elif s.startswith("rotationrate:"):
            val = s.split(":", 1)[1].strip().lower()
            if val in ("0", "solid-state", "non-rotating"):
                cur.kind = "SSD"
            elif val.isdigit() and int(val) > 0:
                cur.kind = "HDD"
    if cur is not None:
        drives.append(cur)
    return drives


def collect_drives() -> List[Drive]:
    sysname = platform.system()
    if sysname == "Linux":
        return collect_drives_linux()
    if sysname == "Darwin":
        return collect_drives_macos()
    if sysname == "FreeBSD":
        return collect_drives_freebsd()
    return []


# ─────────────────────────────────────────────────────────────────────────────
#  COLLECTORS — ZFS
# ─────────────────────────────────────────────────────────────────────────────

def collect_zpools() -> List[ZPool]:
    if not which("zpool"):
        return []
    # -H: no header, tab-separated.  -p: parsable (bytes) for size/alloc/free.
    rc, out, _ = run([
        "zpool", "list", "-H", "-p",
        "-o", "name,size,alloc,free,frag,cap,dedup,health",
    ])
    if rc != 0 or not out.strip():
        return []

    pools: List[ZPool] = []
    for line in out.splitlines():
        parts = line.split("\t")
        if len(parts) < 8:
            parts = line.split()
        if len(parts) < 8:
            continue
        name, size_s, alloc_s, free_s, frag_s, cap_s, dedup_s, health = parts[:8]

        def _to_int(s: str) -> Optional[int]:
            try:
                return int(s)
            except ValueError:
                return parse_size_suffixed(s)

        pool = ZPool(
            name=name,
            size=_to_int(size_s),
            alloc=_to_int(alloc_s),
            free=_to_int(free_s),
            frag=frag_s if frag_s != "-" else None,
            cap=cap_s if cap_s != "-" else None,
            dedup=dedup_s if dedup_s != "-" else None,
            health=health or "UNKNOWN",
        )
        # Ask for a one-line error summary.
        rc2, status, _ = run(["zpool", "status", "-x", name])
        if rc2 == 0 and status.strip():
            pool.errors = status.strip().splitlines()[0]
        pools.append(pool)
    return pools


# ─────────────────────────────────────────────────────────────────────────────
#  REPORT ASSEMBLY
# ─────────────────────────────────────────────────────────────────────────────

def build_report() -> Report:
    rep = Report(
        hostname=platform.node() or "localhost",
        system=platform.system(),
        release=platform.release(),
    )
    try:
        rep.filesystems = collect_filesystems()
    except Exception as exc:  # pragma: no cover — defensive
        rep.notes.append(f"filesystem collection failed: {exc}")
    try:
        rep.drives = collect_drives()
    except Exception as exc:  # pragma: no cover — defensive
        rep.notes.append(f"drive collection failed: {exc}")
    try:
        rep.zpools = collect_zpools()
    except Exception as exc:  # pragma: no cover — defensive
        rep.notes.append(f"zpool collection failed: {exc}")
    return rep


# ─────────────────────────────────────────────────────────────────────────────
#  RENDERING — TEXT / ANSI
# ─────────────────────────────────────────────────────────────────────────────

# Visual thresholds for usage coloring.
USAGE_WARN = 75.0
USAGE_CRIT = 90.0


def _pct_color(pct: float, pal: Palette) -> str:
    if pct >= USAGE_CRIT:
        return pal.bad
    if pct >= USAGE_WARN:
        return pal.warn
    return pal.ok


def _health_color(health: str, pal: Palette) -> str:
    h = (health or "").upper()
    if h == "ONLINE":
        return pal.ok
    if h in ("DEGRADED", "OFFLINE", "REMOVED"):
        return pal.warn
    if h in ("FAULTED", "UNAVAIL"):
        return pal.bad
    return pal.subtle


def progress_bar(pct: float, width: int, pal: Palette) -> str:
    pct = max(0.0, min(100.0, pct))
    filled = int(round(width * pct / 100.0))
    empty = width - filled
    color = _pct_color(pct, pal)
    return (
        f"{color}{GLYPHS['bar_full'] * filled}{pal.reset}"
        f"{pal.subtle}{GLYPHS['bar_empty'] * empty}{pal.reset}"
    )


def banner(title: str, subtitle: str, width: int, pal: Palette) -> str:
    top    = GLYPHS["tl"] + GLYPHS["h"] * (width - 2) + GLYPHS["tr"]
    bottom = GLYPHS["bl"] + GLYPHS["h"] * (width - 2) + GLYPHS["br"]

    # Title line — centered, bold.
    inner = width - 2
    t_pad = max(0, (inner - _visible_len(title)) // 2)
    t_line = (
        GLYPHS["v"]
        + " " * t_pad
        + f"{pal.heading}{title}{pal.reset}"
        + " " * (inner - t_pad - _visible_len(title))
        + GLYPHS["v"]
    )
    # Subtitle line.
    s_pad = max(0, (inner - _visible_len(subtitle)) // 2)
    s_line = (
        GLYPHS["v"]
        + " " * s_pad
        + f"{pal.subtle}{subtitle}{pal.reset}"
        + " " * (inner - s_pad - _visible_len(subtitle))
        + GLYPHS["v"]
    )
    return "\n".join([
        f"{pal.accent}{top}{pal.reset}",
        f"{pal.accent}{t_line}{pal.reset}",
        f"{pal.accent}{s_line}{pal.reset}",
        f"{pal.accent}{bottom}{pal.reset}",
    ])


_ansi_re = re.compile(r"\x1b\[[0-9;]*m")

def _visible_len(s: str) -> int:
    return len(_ansi_re.sub("", s))


def _pad(s: str, width: int, align: str = "left") -> str:
    vis = _visible_len(s)
    if vis >= width:
        return s
    slack = width - vis
    if align == "right":
        return " " * slack + s
    if align == "center":
        left = slack // 2
        right = slack - left
        return " " * left + s + " " * right
    return s + " " * slack


def section_header(title: str, pal: Palette) -> str:
    return (
        f"\n{pal.accent}{GLYPHS['h'] * 3}{pal.reset} "
        f"{pal.heading}{title}{pal.reset} "
        f"{pal.accent}{GLYPHS['h'] * 3}{pal.reset}"
    )


def render_filesystems(fss: List[Filesystem], pal: Palette) -> str:
    if not fss:
        return f"{pal.subtle}  (no filesystems reported){pal.reset}"

    # Each filesystem is rendered as a two-line block so long mount paths
    # never push the stats columns out of alignment:
    #
    #   /very/long/path  (ext4)
    #     › /dev/nvme0n1p2
    #          500.0 GiB used · 1.5 TiB free of 2.0 TiB    76.2%  ████████████████░░░░
    #
    fstype_w = max(4, min(10, max(_visible_len(f.fstype) for f in fss)))
    indent   = "    "  # stats row indent

    lines: List[str] = []
    for i, fs in enumerate(fss):
        pct     = fs.percent
        pct_col = _pct_color(pct, pal)
        bar     = progress_bar(pct, 24, pal)
        pct_str = f"{pct_col}{pct:5.1f}%{pal.reset}"

        # Header line: mount + fstype badge.
        header = (
            f"  {pal.label}{fs.mount}{pal.reset}  "
            f"{pal.subtle}({fs.fstype.strip()}){pal.reset}"
        )
        lines.append(header)

        # Optional source line (skip noisy/empty values).
        if (fs.source and fs.source not in ("none", "-", "—")
                and not fs.source.startswith("/dev/loop")):
            lines.append(
                f"{indent}{pal.subtle}{GLYPHS['arrow']} {fs.source}{pal.reset}"
            )

        # Stats line — a human-readable sentence plus bar + percentage.
        summary = (
            f"{pal.value}{human_bytes(fs.used)}{pal.reset} used"
            f" {pal.subtle}·{pal.reset} "
            f"{pal.value}{human_bytes(fs.avail)}{pal.reset} free of "
            f"{pal.value}{human_bytes(fs.size)}{pal.reset}"
        )
        lines.append(f"{indent}{summary}")
        lines.append(f"{indent}{bar}  {pct_str}")

        # Blank line between entries (but not after the last one).
        if i < len(fss) - 1:
            lines.append("")

    # Keep fstype_w referenced so lint is happy if we want to reintroduce a
    # compact mode later; it's intentionally computed above.
    _ = fstype_w
    return "\n".join(lines)


def render_drives(drives: List[Drive], pal: Palette) -> str:
    if not drives:
        return f"{pal.subtle}  (no physical drives detected){pal.reset}"
    name_w  = max(8, max(_visible_len(d.name) for d in drives))
    kind_w  = max(4, max(_visible_len(d.kind or "—") for d in drives))

    lines = []
    lines.append(
        f"  {pal.label}{_pad('Device', name_w)}{pal.reset}  "
        f"{pal.label}{_pad('Kind', kind_w)}{pal.reset}  "
        f"{pal.label}{_pad('Size', 10, 'right')}{pal.reset}  "
        f"{pal.label}Model{pal.reset}"
    )
    for d in drives:
        lines.append(
            f"  {pal.value}{_pad(d.name, name_w)}{pal.reset}  "
            f"{pal.accent}{_pad(d.kind or '—', kind_w)}{pal.reset}  "
            f"{_pad(human_bytes(d.size), 10, 'right')}  "
            f"{pal.subtle}{d.model or '—'}{pal.reset}"
        )
    return "\n".join(lines)


def render_zpools(pools: List[ZPool], pal: Palette) -> str:
    if not pools:
        return f"{pal.subtle}  (no ZFS pools){pal.reset}"

    lines = []
    for p in pools:
        hc = _health_color(p.health, pal)
        icon = GLYPHS["check"] if p.health.upper() == "ONLINE" else GLYPHS["warn"]

        pct_val: Optional[float] = None
        if p.size and p.alloc is not None:
            pct_val = p.alloc / p.size * 100.0

        header = (
            f"  {pal.label}{p.name}{pal.reset}   "
            f"{hc}{icon} {p.health}{pal.reset}"
        )
        lines.append(header)

        def kv(k: str, v: str) -> str:
            return (f"    {pal.subtle}{GLYPHS['bullet']}{pal.reset} "
                    f"{pal.label}{_pad(k, 9)}{pal.reset} {pal.value}{v}{pal.reset}")

        lines.append(kv("size",  human_bytes(p.size)))
        lines.append(kv("alloc", human_bytes(p.alloc)))
        lines.append(kv("free",  human_bytes(p.free)))
        if p.frag:  lines.append(kv("frag",  p.frag))
        if p.dedup: lines.append(kv("dedup", p.dedup))
        if p.cap:   lines.append(kv("cap",   p.cap))

        if pct_val is not None:
            bar = progress_bar(pct_val, 28, pal)
            pct_str = f"{_pct_color(pct_val, pal)}{pct_val:5.1f}%{pal.reset}"
            lines.append(f"    {bar}  {pct_str}")

        if p.errors:
            lines.append(f"    {pal.subtle}{p.errors}{pal.reset}")
        lines.append("")
    return "\n".join(lines).rstrip()


def render_text(report: Report, pal: Palette, width: int = 78) -> str:
    title = f"  Storage Report — {report.hostname}  "
    sub   = f"  {report.system} {report.release}  "
    out: List[str] = []
    out.append(banner(title, sub, width, pal))
    out.append(section_header("Filesystems", pal))
    out.append(render_filesystems(report.filesystems, pal))
    out.append(section_header("Physical Drives", pal))
    out.append(render_drives(report.drives, pal))
    out.append(section_header("ZFS Pools", pal))
    out.append(render_zpools(report.zpools, pal))

    if report.notes:
        out.append(section_header("Notes", pal))
        for n in report.notes:
            out.append(f"  {pal.warn}{GLYPHS['warn']}{pal.reset} {n}")

    out.append("")
    out.append(f"{pal.subtle}  diskstats {SCRIPT_VERSION}  ·  "
               f"generated on {report.hostname}{pal.reset}")
    return "\n".join(out)


# ─────────────────────────────────────────────────────────────────────────────
#  RENDERING — HTML (for emails)
# ─────────────────────────────────────────────────────────────────────────────

def _esc(s: str) -> str:
    return (s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;"))


def _html_bar(pct: float) -> str:
    pct = max(0.0, min(100.0, pct))
    if pct >= USAGE_CRIT:
        color = "#e06c75"
    elif pct >= USAGE_WARN:
        color = "#e5c07b"
    else:
        color = "#98c379"
    return (
        f'<div style="width:180px;height:10px;background:#2c313a;'
        f'border-radius:4px;overflow:hidden;display:inline-block;'
        f'vertical-align:middle;">'
        f'<div style="width:{pct:.1f}%;height:100%;background:{color};"></div>'
        f'</div>'
    )


def render_html(report: Report) -> str:
    font = ("-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,"
            "Arial,sans-serif")
    mono = "ui-monospace,'SF Mono',Menlo,Consolas,monospace"
    css_table = ('width:100%;border-collapse:collapse;font-size:13px;'
                 'font-family:' + mono + ';')
    css_th = ('text-align:left;padding:6px 10px;border-bottom:1px solid #3a3f4b;'
              'color:#c8ccd4;font-weight:600;background:#242830;')
    css_td = 'padding:6px 10px;border-bottom:1px solid #2c313a;color:#d7dae0;'
    css_td_r = css_td + 'text-align:right;'

    parts: List[str] = []
    parts.append(
        '<div style="background:#1e222a;color:#d7dae0;padding:24px;'
        f'font-family:{font};max-width:820px;border-radius:8px;">'
    )
    parts.append(
        f'<div style="font-size:20px;font-weight:600;color:#61afef;">'
        f'Storage Report &mdash; {_esc(report.hostname)}</div>'
        f'<div style="font-size:13px;color:#8a8f99;margin-bottom:18px;">'
        f'{_esc(report.system)} {_esc(report.release)}</div>'
    )

    # Filesystems
    parts.append('<h3 style="color:#61afef;margin:16px 0 8px;font-size:15px;">'
                 'Filesystems</h3>')
    parts.append(f'<table style="{css_table}">')
    parts.append(
        f'<tr><th style="{css_th}">Mount</th><th style="{css_th}">Type</th>'
        f'<th style="{css_th};text-align:right;">Size</th>'
        f'<th style="{css_th};text-align:right;">Used</th>'
        f'<th style="{css_th};text-align:right;">Free</th>'
        f'<th style="{css_th};text-align:right;">Use%</th>'
        f'<th style="{css_th}">Usage</th></tr>'
    )
    for fs in report.filesystems:
        parts.append(
            '<tr>'
            f'<td style="{css_td}"><div>{_esc(fs.mount)}</div>'
            f'<div style="font-size:11px;color:#8a8f99;">{_esc(fs.source)}</div></td>'
            f'<td style="{css_td}">{_esc(fs.fstype)}</td>'
            f'<td style="{css_td_r}">{_esc(human_bytes(fs.size))}</td>'
            f'<td style="{css_td_r}">{_esc(human_bytes(fs.used))}</td>'
            f'<td style="{css_td_r}">{_esc(human_bytes(fs.avail))}</td>'
            f'<td style="{css_td_r}">{fs.percent:.1f}%</td>'
            f'<td style="{css_td}">{_html_bar(fs.percent)}</td>'
            '</tr>'
        )
    parts.append('</table>')

    # Drives
    parts.append('<h3 style="color:#61afef;margin:20px 0 8px;font-size:15px;">'
                 'Physical Drives</h3>')
    parts.append(f'<table style="{css_table}">')
    parts.append(
        f'<tr><th style="{css_th}">Device</th><th style="{css_th}">Kind</th>'
        f'<th style="{css_th};text-align:right;">Size</th>'
        f'<th style="{css_th}">Model</th></tr>'
    )
    if not report.drives:
        parts.append(f'<tr><td style="{css_td}" colspan="4">'
                     '<em>(none detected)</em></td></tr>')
    for d in report.drives:
        parts.append(
            '<tr>'
            f'<td style="{css_td}">{_esc(d.name)}</td>'
            f'<td style="{css_td}">{_esc(d.kind or "—")}</td>'
            f'<td style="{css_td_r}">{_esc(human_bytes(d.size))}</td>'
            f'<td style="{css_td};color:#8a8f99;">{_esc(d.model or "—")}</td>'
            '</tr>'
        )
    parts.append('</table>')

    # ZFS
    parts.append('<h3 style="color:#61afef;margin:20px 0 8px;font-size:15px;">'
                 'ZFS Pools</h3>')
    if not report.zpools:
        parts.append('<div style="color:#8a8f99;font-size:13px;">'
                     '<em>(no pools)</em></div>')
    else:
        parts.append(f'<table style="{css_table}">')
        parts.append(
            f'<tr><th style="{css_th}">Pool</th><th style="{css_th}">Health</th>'
            f'<th style="{css_th};text-align:right;">Size</th>'
            f'<th style="{css_th};text-align:right;">Alloc</th>'
            f'<th style="{css_th};text-align:right;">Free</th>'
            f'<th style="{css_th}">Usage</th></tr>'
        )
        for p in report.zpools:
            pct_val = (p.alloc / p.size * 100.0) if (p.size and p.alloc is not None) else 0.0
            h = (p.health or "").upper()
            hcolor = "#98c379" if h == "ONLINE" else (
                "#e5c07b" if h in ("DEGRADED", "OFFLINE", "REMOVED") else "#e06c75"
            )
            parts.append(
                '<tr>'
                f'<td style="{css_td}">{_esc(p.name)}</td>'
                f'<td style="{css_td};color:{hcolor};font-weight:600;">{_esc(p.health)}</td>'
                f'<td style="{css_td_r}">{_esc(human_bytes(p.size))}</td>'
                f'<td style="{css_td_r}">{_esc(human_bytes(p.alloc))}</td>'
                f'<td style="{css_td_r}">{_esc(human_bytes(p.free))}</td>'
                f'<td style="{css_td}">{_html_bar(pct_val)} '
                f'<span style="color:#8a8f99;font-size:12px;">{pct_val:.1f}%</span></td>'
                '</tr>'
            )
        parts.append('</table>')

    parts.append(
        '<div style="margin-top:20px;font-size:11px;color:#6b6f79;">'
        f'diskstats {SCRIPT_VERSION} &middot; generated on '
        f'{_esc(report.hostname)}</div>'
    )
    parts.append('</div>')
    return "".join(parts)


# ─────────────────────────────────────────────────────────────────────────────
#  ENTRYPOINT
# ─────────────────────────────────────────────────────────────────────────────

def _terminal_supports_color() -> bool:
    if not sys.stdout.isatty():
        return False
    if os.environ.get("NO_COLOR"):
        return False
    if os.environ.get("TERM") == "dumb":
        return False
    return True


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        prog="diskstats",
        description="Cross-platform disk & storage report (macOS / Linux / FreeBSD).",
    )
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--color",    action="store_true",
                   help="force colorized output")
    g.add_argument("--no-color", action="store_true",
                   help="disable ANSI color codes")
    g.add_argument("--html",     action="store_true",
                   help="emit inline-styled HTML (for emails)")
    ap.add_argument("--width", type=int, default=78,
                    help="width of the banner (default: 78)")
    ap.add_argument("--version", action="version",
                    version=f"diskstats {SCRIPT_VERSION}")
    return ap.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(list(argv) if argv is not None else sys.argv[1:])
    report = build_report()

    if args.html:
        print(render_html(report))
        return 0

    if args.color:
        use_color = True
    elif args.no_color:
        use_color = False
    else:
        use_color = _terminal_supports_color()

    pal = Palette(enabled=use_color)
    print(render_text(report, pal, width=max(40, args.width)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
